/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sridhar */

#ifndef _Included_Sridhar
#define _Included_Sridhar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sridhar
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Sridhar_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
